I see that if I did not filled any API key the features are not disabled...and I can create a new story but I will get an error: "Runtime Error Server
TypeError: Cannot read properties of undefined (reading 'extend')

src/actions/storyActions.ts (68:59) @ eval

  66 |
  67 | // Schemas to be used in server actions, possibly extended if needed
> 68 | const GenerateTitleInputServerSchema = AITitleInputSchema.extend({ userId: z.string() });
     |                                                           ^
  69 | export type GenerateTitleInput = z.infer<typeof GenerateTitleInputServerSchema>;
  70 |
  71 | const GenerateScriptInputServerSchema = AIScriptInputSchema.extend({ userId: z.string() });
Call Stack
5

Show 4 ignore-listed frame(s)
eval
src/actions/storyActions.ts (68:59)"

I expect instead to deactivate all buttons for users that did not configured the APIs